volunteer-filtering
ctc-uci/abound-food-care-backend pull request #97
Opened 2022-08-17 17:48 UTC by ctc-devops

making routes for volunteering filtering
closes #96

2022-08-19 07:03 UTC, alanchangxyz approved these changes
Still needs [pagination](https://levelup.gitconnected.com/creating-a-data-pagination-function-in-postgresql-2a032084af54) but we finish that up in the next week

2022-09-02 03:41 UTC, ctc-devops commented on routes/volunteers/volunteers.js
> +    console.log(req.body);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-02 03:41 UTC, ctc-devops commented on routes/volunteers/volunteers.js
> +    console.log(req.query);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-02 03:41 UTC, ctc-devops commented on routes/volunteers/volunteers.js
> +    console.log(req.params);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-08 09:25 UTC, alanchangxyz requested changes
some syntax things and then pls edit the pr title/description to reflect what got changed here 👍 after that happens we'll be good on this pr

2022-09-08 09:25 UTC, alanchangxyz commented on routes/volunteers/volunteers.js
> +    } else if (driverOption === 'Food Running') {
this should be `eventInterest` but it's getting changed anyways; see my convert to mappings comment above

2022-09-08 09:25 UTC, alanchangxyz commented on routes/volunteers/volunteers.js
> +    let { rows: volunteers } = await pool.query(
see my comment about `let` variables above; whatever you do up there just do it down here again

2022-09-08 09:25 UTC, alanchangxyz commented on routes/volunteers/volunteers.js
> +    }
can we convert these `let` variables and the following `if/else` loops to mappings/dictionaries pls - also we need a default case if the `driverOption` or `eventInterest` isn't one of the two values (which you can probably use the `TRUE` strings for)

2022-09-08 09:25 UTC, alanchangxyz commented on routes/volunteers/volunteers.js
> +    }
see my mappings comment on the above route

2022-09-08 09:25 UTC, alanchangxyz commented on routes/volunteers/volunteers.js
> +    res.status(200).json(keysToCamel(volunteers));
in general `let` variables are pretty bad for maintainability and we should avoid using them whenever possible; I would feel better about making `volunteers` a `const` and then making + returning a new name/object for whatever you decide to manipulate it into later on

2022-09-12 00:45 UTC, alanchangxyz approved these changes
LGTM

2022-09-12 03:14 UTC, merged